name : first pipeline 

on :
  push:
    branches:
      - main

jobs :
  greet :

    runs-on: ubuntu-latest
    steps :
    - name: checkout the code
      run: actions/checkout@v4

    - name: say hello from github actions
      run: echo "Hello, From GitHub Actions"
