name : first pipeline 

on :
  push:
    branches:
      - main
jobs :
  greet :

    runs-on: ubuntu-latest
    steps :
      - name: checkout the code
        uses: actions/checkout@v4 

      - name: say hello from github actions
        run: echo "Hello, From GitHub Actions"

      - name: current date
        run: date 

      - name: branch name
        run: echo "Name of the branch is ${{ github.ref_name }}"

      - name: list the files in the rep 
        run: ls -la

      - name: Operating system 
        run: echo "The operating system is ${{ runner.os}}" 

